name: Update Gradle Wrapper
on: [push, pull_request]

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd example/android
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: master
